# 1. Install VS Code extension 'humao.rest-client' to use this file

@HOST = http://localhost:4444
@API = {{HOST}}/api/v1

### Request: Check readiness
# @name getReadiness
GET {{HOST}}/checks/readiness HTTP/1.1

# The corresponding bearer token

#######################################################
# PUBLIC API
#######################################################

### Post Donation
# @name postDonation
POST {{API}}/donations HTTP/1.1
Content-Type: application/json

{
    "postalCode": "12345",
    "riskCase": 1
}
