# kubetpl:syntax:go-template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .APP }}-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .APP }}-secret
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: dbName
              name: {{ .APP }}-configmap
        image: postgres:10.4
        imagePullPolicy: IfNotPresent
        name: postgres
        ports:
          - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
  type: ClusterIP
